---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/mysql
configMapGenerator:
- name: mysql-values-overrides
  files:
  - values.yaml=values-overrides.yaml
