---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: banzaicloud
  namespace: flux-system
spec:
  interval: 720h
  timeout: 5m
  url: https://kubernetes-charts.banzaicloud.com
