---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/drupal
configMapGenerator:
- name: drupal-values-overrides
  files:
  - values.yaml=values-overrides.yaml
