---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 3m
  dependsOn:
    - name: repositories
  path: ./deploy/infrastructure/overlays/demo
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
