apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: drupal
spec:
  interval: 720h
  chart:
    spec:
      chart: drupal
      version: '13.0.9'
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 720h
  upgrade:
    remediation:
      remediateLastFailure: true
  values:
  valuesFrom:
    - kind: ConfigMap
      name: drupal-values
    - kind: ConfigMap
      name: drupal-values-overrides
