fullnameOverride: drupal
persistence:
  enabled: false
mariadb:
  enabled: false
externalDatabase:
  host: ""
  user: bn_drupal
  password: ""
  database: bitnami_drupal
drupalPassword: demo
