apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: joomla
spec:
  interval: 720h
  chart:
    spec:
      chart: joomla
      version: '13.3.16'
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 720h
  upgrade:
    remediation:
      remediateLastFailure: true
  values:
  valuesFrom:
    - kind: ConfigMap
      name: joomla-values
    - kind: ConfigMap
      name: joomla-values-overrides
